config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'user/new'
  get 'users/new'
  get 'article/new'
  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'resumes/specialists'
  get 'resumes/read'
  root 'resumes#main'

  resources :post, only: %i[index new create destroy]
  resources :electrics, only: %i[index new create destroy]
  resources :equis, only: %i[index new create destroy]
  resources :repairs, only: %i[index new create destroy]
  resources :resumes, only: %i[index new create destroy]
  resources :leaks, only: %i[index new create destroy]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/electric.rb
# frozen_string_literal: true

class Electric < ApplicationRecord
end

app/models/equi.rb
# frozen_string_literal: true

class Equi < ApplicationRecord
end

app/models/leak.rb
# frozen_string_literal: true

class Leak < ApplicationRecord
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
end

app/models/repair.rb
class Repair < ApplicationRecord
end

app/models/resume.rb
# frozen_string_literal: true

class Resume < ActiveRecord::Base
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  # Возвращает дайджест для указанной строки
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/ar_controller.rb
# frozen_string_literal: true

class ArController < ApplicationController
  def new; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def about; end
end

app/controllers/resumes_controller.rb
# frozen_string_literal: true

class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to resumes_read_path
    else
      render 'new'
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice: 'Обьявление удалено'
  end

  private

  def resume_params
    params.require(:resume).permit(:phone, :addres, :comment, :spesc, :fio)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # титул полученый из вьюхи
  def full_title(page_title = '')
    base_title = 'RKS-Samara' # базовый титул
    if page_title.empty? # если титула в вьюхе нет то
      base_title # базовый титул
    else # иначе
      "#{page_title} | #{base_title}" # титул из вьюхи и базовый
    end
  end
end

app/helpers/ar_helper.rb
# frozen_string_literal: true

module ArHelper
end

app/helpers/article_helper.rb
# frozen_string_literal: true

module ArticleHelper
end

app/helpers/electrics_helper.rb
# frozen_string_literal: true

module ElectricsHelper
end

app/helpers/equis_helper.rb
# frozen_string_literal: true

module EquisHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/leaks_helper.rb
# frozen_string_literal: true

module LeaksHelper
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/helpers/repairs_helper.rb
# frozen_string_literal: true

module RepairsHelper
end

app/helpers/resumes_helper.rb
# frozen_string_literal: true

module ResumesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Осуществляет вход данного пользователя.
  def log_in(user)
    session[:user_id] = user.id
  end
  # Запоминает пользователя в постоянном сеансе

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  # Закрывает постоянный сеанс.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Осуществляет выход текущего пользователя.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Возвращает граватар для данного пользователя.
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<% provide(:title, 'Диагностика') %>
<h1>Диагностика</h1>
<table class = "table table-bordered table-striped">

    <% @resumes.reverse.each do |resume| %>
    	<div class="row">
        	<div class="col-3">
         		<p>ФИО: <%= resume.fio %></p>
         		<p>Телефон: <%=resume.phone %></p>
         		<p>Адрес: <%=resume.addres %></p>
            </div>
            <div class="col-3"></div>
         	<div class="col-3">
            	<p>Коментарий: <%= resume.comment %></p>
            	<%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger"%>
			</div>
    	</div>
        <hr>
      <% end %>
   </tbody>
</table>

app/views/resumes/main.html.erb
<center><h1>Вызвать мастера</h1>
<%= link_to "Диагностика", new_resume_path, class: "btn btn-primary bottom" %>
<%= link_to "Ремонт", new_repair_path, class: "btn btn-primary bottom" %>
<%= link_to "Установка спец. Оборудования", new_equi_path, class: "btn btn-primary bottom" %>
<%= link_to "Устранение протечки", new_leak_path, class: "btn btn-primary bottom" %>
<%= link_to "Устранение перебоев электросети", new_electric_path, class: "btn btn-primary bottom" %>



</center>

app/views/resumes/new.html.erb
<% provide(:title, 'Создать заявку') %>
<center>
<h1>Создать заявку</h1>

<div class = "well">
   <%= form_for @resume, html: { multipart: true } do |f| %>
      
      <%= f.number_field:phone, placeholder: "Телефон", class: "form-control input_new_pos "%>
      <%= f.text_field :addres, placeholder: "Адрес", class: "form-control input_new_pos "%>

      <%= f.text_field :fio, placeholder: "ФИО", class: "form-control input_new_pos " %>

      <%= f.text_area :comment, class: "form-control input_new_pos ",placeholder: "Коментарий",rows: 7%>
<br/>
      <%= f.submit "Опубликовать", class: "btn btn-primary" %>
   <% end %>
</div>
</center>

app/views/resumes/read.html.erb
<% provide(:title, 'Специалисты') %>
<h1>Заявка принята! специалист свяжется с вами в течении 30 минут</h1>

app/views/resumes/specialists.html.erb
<% provide(:title, 'Специалисты') %>
<center>
<h1>Специалисты</h1>
<%= link_to "Диагностика", resumes_index_path, class: "btn btn-primary bottom" %>
<%= link_to "Ремонт", repairs_index_path, class: "btn btn-primary bottom" %>
<%= link_to "Установка спец. Оборудования", equis_index_path, class: "btn btn-primary bottom" %>
<%= link_to "Устранение протечки", leaks_path, class: "btn btn-primary bottom" %>
<%= link_to "Устранение перебоев электросети", electrics_path, class: "btn btn-primary bottom" %>
</center>