config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'user/new'
  get 'users/new'
  get 'article/new'
  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'resumes/specialists'
  get 'resumes/read'
  root 'resumes#main'

  resources :post, only: %i[index new create destroy]
  resources :electrics, only: %i[index new create destroy]
  resources :equis, only: %i[index new create destroy]
  resources :repairs, only: %i[index new create destroy]
  resources :resumes, only: %i[index new create destroy]
  resources :leaks, only: %i[index new create destroy]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/electric.rb
# frozen_string_literal: true

class Electric < ApplicationRecord
end

app/models/equi.rb
# frozen_string_literal: true

class Equi < ApplicationRecord
end

app/models/leak.rb
# frozen_string_literal: true

class Leak < ApplicationRecord
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
end

app/models/repair.rb
class Repair < ApplicationRecord
end

app/models/resume.rb
# frozen_string_literal: true

class Resume < ActiveRecord::Base
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  # Возвращает дайджест для указанной строки
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/ar_controller.rb
# frozen_string_literal: true

class ArController < ApplicationController
  def new; end
end

app/helpers/ar_helper.rb
# frozen_string_literal: true

module ArHelper
end

app/helpers/article_helper.rb
# frozen_string_literal: true

module ArticleHelper
end

app/helpers/electrics_helper.rb
# frozen_string_literal: true

module ElectricsHelper
end

app/helpers/equis_helper.rb
# frozen_string_literal: true

module EquisHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/leaks_helper.rb
# frozen_string_literal: true

module LeaksHelper
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/helpers/repairs_helper.rb
# frozen_string_literal: true

module RepairsHelper
end

app/helpers/resumes_helper.rb
# frozen_string_literal: true

module ResumesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Осуществляет вход данного пользователя.
  def log_in(user)
    session[:user_id] = user.id
  end
  # Запоминает пользователя в постоянном сеансе

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  # Закрывает постоянный сеанс.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Осуществляет выход текущего пользователя.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Возвращает граватар для данного пользователя.
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<!-- 
<div class="row">
	<div class="col">
	</div>

	<div class="col-8">

	<footer class="footer">
		<small>
			The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
			by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path%></li>

				<li><%= link_to "News", root_path %></li>
			</ul>
		</nav>
	</footer>
	</div>

	<div class="col">
	</div>
</div> -->

app/views/layouts/_header.html.erb
  <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <h5><li><%= link_to "RKS-Samara", '#', id: "logo", class: 'nav-link px-2 ' %></li></h5>  
        
        

        <% if logged_in? %>

       <!--  <%= link_to "Вызовы", post_index_path, class: "nav-link" %> -->
        <%= link_to "Выйти", logout_path, method: "delete", class: 'nav-link'%>
        
        <% else %>
          <%= link_to "Вызвать мастера", root_path, class: "nav-link" %>
          
          <%= link_to "Войти как специалист", login_path, class: 'nav-link'%>

        <%end%>

      </ul>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title> 
    <!-- полный титул полученый из хелпера aplication, (yield(:title)) это подключение ко всем вьюхам раздел титул
     --><meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="hystmodal.min.css">
   
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>





  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="row">

      <div class="col"></div>

      <div class="col-xs-6 col-md-6">
      
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>  
          </div>
        <% end %>
        
        <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      </div>

      <div class="col"></div> 
    </div>
    <%= render 'layouts/footer' %>
  </body>
  <script src="hystmodal.min.js"></script>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id = "error_explanation">
		<div class = "alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>